In [2]:

from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb://rehmandataguy_db_user:qN5qzuCBcwoT6hRn@ac-e61qcjo-shard-00-00.8gndk2p.mongodb.net:27017,ac-e61qcjo-shard-00-01.8gndk2p.mongodb.net:27017,ac-e61qcjo-shard-00-02.8gndk2p.mongodb.net:27017/?ssl=true&replicaSet=atlas-gzh4uc-shard-0&authSource=admin&appName=Cluster0"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

In [3]:
try:
    client.admin.command('ping')
    print("Hello world, connected to mongodb")
except Exception as e:
    print(f"Error {e}")

Hello world, connected to mongodb

In [4]:


client.list_database_names()

['sample_mflix', 'ultimate_data_science_b2', 'admin', 'local']

In [5]:
db = client.ultimate_data_science_b2

In [6]:
db.list_collection_names()

['dummy0']

In [7]:
collection = db.dummy0

In [8]:
for i in collection.find():
    print(i)

{'_id': ObjectId('69c56ef793b84555ae26aac5'), 'name': 'AbdulrehmanShaikh', 'paid': 8000, 'batch': '2', 'phone': '8197293490'}
{'_id': ObjectId('69c582a7f9fd99f12b921697'), 'name': 'Vinay Dyanand Naik', 'batch': '2', 'paid': 8000, 'phone': '9449775313'}
{'_id': ObjectId('69c58d3b112b95f9ba5c2a88'), 'name': 'Shivam K', 'paid': 8000, 'batch': '2', 'phone': '8197293490'}
{'_id': ObjectId('69c58e2a112b95f9ba5c2a89'), 'name': 'Karthik', 'paid': 8000, 'batch': '2', 'phone': '8197293490'}
{'_id': ObjectId('69c5d323562c4300fd09d971'), 'name': 'Karthik', 'paid': 8000, 'batch': '2', 'phone': '8197293490'}

In [9]:
query = {
    "paid":{"$exists":True}
}

for i in collection.find(query):
    print(i)

{'_id': ObjectId('69c56ef793b84555ae26aac5'), 'name': 'AbdulrehmanShaikh', 'paid': 8000, 'batch': '2', 'phone': '8197293490'}
{'_id': ObjectId('69c582a7f9fd99f12b921697'), 'name': 'Vinay Dyanand Naik', 'batch': '2', 'paid': 8000, 'phone': '9449775313'}
{'_id': ObjectId('69c58d3b112b95f9ba5c2a88'), 'name': 'Shivam K', 'paid': 8000, 'batch': '2', 'phone': '8197293490'}
{'_id': ObjectId('69c58e2a112b95f9ba5c2a89'), 'name': 'Karthik', 'paid': 8000, 'batch': '2', 'phone': '8197293490'}
{'_id': ObjectId('69c5d323562c4300fd09d971'), 'name': 'Karthik', 'paid': 8000, 'batch': '2', 'phone': '8197293490'}

In [10]:
query = {
    "paid" : {"$gt":5000}
}
for i in collection.find(query):
    print(i)

{'_id': ObjectId('69c56ef793b84555ae26aac5'), 'name': 'AbdulrehmanShaikh', 'paid': 8000, 'batch': '2', 'phone': '8197293490'}
{'_id': ObjectId('69c582a7f9fd99f12b921697'), 'name': 'Vinay Dyanand Naik', 'batch': '2', 'paid': 8000, 'phone': '9449775313'}
{'_id': ObjectId('69c58d3b112b95f9ba5c2a88'), 'name': 'Shivam K', 'paid': 8000, 'batch': '2', 'phone': '8197293490'}
{'_id': ObjectId('69c58e2a112b95f9ba5c2a89'), 'name': 'Karthik', 'paid': 8000, 'batch': '2', 'phone': '8197293490'}
{'_id': ObjectId('69c5d323562c4300fd09d971'), 'name': 'Karthik', 'paid': 8000, 'batch': '2', 'phone': '8197293490'}

In [11]:
query = {
    "name": "Shivam K",
    "paid": 10000, 
    "batch": "2",
    "phone": "8197293490"
}
for i in collection.find():
    print(i)

{'_id': ObjectId('69c56ef793b84555ae26aac5'), 'name': 'AbdulrehmanShaikh', 'paid': 8000, 'batch': '2', 'phone': '8197293490'}
{'_id': ObjectId('69c582a7f9fd99f12b921697'), 'name': 'Vinay Dyanand Naik', 'batch': '2', 'paid': 8000, 'phone': '9449775313'}
{'_id': ObjectId('69c58d3b112b95f9ba5c2a88'), 'name': 'Shivam K', 'paid': 8000, 'batch': '2', 'phone': '8197293490'}
{'_id': ObjectId('69c58e2a112b95f9ba5c2a89'), 'name': 'Karthik', 'paid': 8000, 'batch': '2', 'phone': '8197293490'}
{'_id': ObjectId('69c5d323562c4300fd09d971'), 'name': 'Karthik', 'paid': 8000, 'batch': '2', 'phone': '8197293490'}

In [12]:
## inserting 

query = {
    "name": "Karthik",
    "paid" : 10000,
    'batch': "2",
    "phone":"8197293490"
}

result= collection.insert_one(query)

In [13]:
## updating 

filter_query = {
    "paid":10000
}

update_query = {
    "$set":{
        "paid":8000
    }
}

collection.update_many(filter_query, update_query)

UpdateResult({'n': 1, 'electionId': ObjectId('7fffffff000000000000016a'), 'opTime': {'ts': Timestamp(1774572871, 3), 't': 362}, 'nModified': 1, 'ok': 1.0, '$clusterTime': {'clusterTime': Timestamp(1774572871, 3), 'signature': {'hash': b'\x8d\xf2u\x9dy,\x81\xeb\x13\x8d\xb8|\xba\xf7u\xe8\x11|=V', 'keyId': 7575219830693822466}}, 'operationTime': Timestamp(1774572871, 3), 'updatedExisting': True}, acknowledged=True)

In [14]:
for i in collection.find():
    print(i)

{'_id': ObjectId('69c56ef793b84555ae26aac5'), 'name': 'AbdulrehmanShaikh', 'paid': 8000, 'batch': '2', 'phone': '8197293490'}
{'_id': ObjectId('69c582a7f9fd99f12b921697'), 'name': 'Vinay Dyanand Naik', 'batch': '2', 'paid': 8000, 'phone': '9449775313'}
{'_id': ObjectId('69c58d3b112b95f9ba5c2a88'), 'name': 'Shivam K', 'paid': 8000, 'batch': '2', 'phone': '8197293490'}
{'_id': ObjectId('69c58e2a112b95f9ba5c2a89'), 'name': 'Karthik', 'paid': 8000, 'batch': '2', 'phone': '8197293490'}
{'_id': ObjectId('69c5d323562c4300fd09d971'), 'name': 'Karthik', 'paid': 8000, 'batch': '2', 'phone': '8197293490'}
{'_id': ObjectId('69c5d546b7fa40dd6ff7f66e'), 'name': 'Karthik', 'paid': 8000, 'batch': '2', 'phone': '8197293490'}

In [15]:
data = []
for i in collection.find():
    data.append(i)

In [16]:
import pandas as pd

In [17]:
df = pd.DataFrame(data)

In [18]:
df.head(10)

                        _id                name  paid batch       phone
0  69c56ef793b84555ae26aac5   AbdulrehmanShaikh  8000     2  8197293490
1  69c582a7f9fd99f12b921697  Vinay Dyanand Naik  8000     2  9449775313
2  69c58d3b112b95f9ba5c2a88            Shivam K  8000     2  8197293490
3  69c58e2a112b95f9ba5c2a89             Karthik  8000     2  8197293490
4  69c5d323562c4300fd09d971             Karthik  8000     2  8197293490
5  69c5d546b7fa40dd6ff7f66e             Karthik  8000     2  8197293490

In [20]:
df = df.drop_duplicates(subset=["name"], keep="first").copy()

In [21]:
df

                        _id                name  paid batch       phone
0  69c56ef793b84555ae26aac5   AbdulrehmanShaikh  8000     2  8197293490
1  69c582a7f9fd99f12b921697  Vinay Dyanand Naik  8000     2  9449775313
2  69c58d3b112b95f9ba5c2a88            Shivam K  8000     2  8197293490
3  69c58e2a112b95f9ba5c2a89             Karthik  8000     2  8197293490

In [23]:
query = {
    "name" : {"$exists":True}
}

collection.delete_many(query)

DeleteResult({'n': 6, 'electionId': ObjectId('7fffffff000000000000016a'), 'opTime': {'ts': Timestamp(1774572984, 3), 't': 362}, 'ok': 1.0, '$clusterTime': {'clusterTime': Timestamp(1774572984, 3), 'signature': {'hash': b'#\x0b\xe3\x93\r\x94+\xfc\x08\x85\x83\x87P\xf9\xf5\xbc~:V0', 'keyId': 7575219830693822466}}, 'operationTime': Timestamp(1774572984, 3)}, acknowledged=True)

In [24]:
for i in collection.find():
    print(i)

In [34]:
data = df.to_dict("records")

In [35]:
data

[{'_id': ObjectId('69c56ef793b84555ae26aac5'),
  'name': 'AbdulrehmanShaikh',
  'paid': 8000,
  'batch': '2',
  'phone': '8197293490'},
 {'_id': ObjectId('69c582a7f9fd99f12b921697'),
  'name': 'Vinay Dyanand Naik',
  'paid': 8000,
  'batch': '2',
  'phone': '9449775313'},
 {'_id': ObjectId('69c58d3b112b95f9ba5c2a88'),
  'name': 'Shivam K',
  'paid': 8000,
  'batch': '2',
  'phone': '8197293490'},
 {'_id': ObjectId('69c58e2a112b95f9ba5c2a89'),
  'name': 'Karthik',
  'paid': 8000,
  'batch': '2',
  'phone': '8197293490'}]

In [36]:
collection.insert_many(data)

InsertManyResult([ObjectId('69c56ef793b84555ae26aac5'), ObjectId('69c582a7f9fd99f12b921697'), ObjectId('69c58d3b112b95f9ba5c2a88'), ObjectId('69c58e2a112b95f9ba5c2a89')], acknowledged=True)

In [37]:
for i in collection.find():
    print(i)

{'_id': ObjectId('69c56ef793b84555ae26aac5'), 'name': 'AbdulrehmanShaikh', 'paid': 8000, 'batch': '2', 'phone': '8197293490'}
{'_id': ObjectId('69c582a7f9fd99f12b921697'), 'name': 'Vinay Dyanand Naik', 'paid': 8000, 'batch': '2', 'phone': '9449775313'}
{'_id': ObjectId('69c58d3b112b95f9ba5c2a88'), 'name': 'Shivam K', 'paid': 8000, 'batch': '2', 'phone': '8197293490'}
{'_id': ObjectId('69c58e2a112b95f9ba5c2a89'), 'name': 'Karthik', 'paid': 8000, 'batch': '2', 'phone': '8197293490'}