In [1]:
import pandas as pd

In [18]:

df = pd.read_excel("studentdata.xlsx")
df.info()
df

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student id  4 non-null      int64
 1   Name        4 non-null      str
 2   Score       4 non-null      int64
 3   Rank        4 non-null      int64
dtypes: int64(3), str(1)
memory usage: 260.0 bytes

   Student id    Name  Score  Rank
0         101   Vinay    540     4
1         102    Anup    560     3
2         103   Abdul    620     1
3         104  Ganesh    600     2

In [35]:
def add_student():
    import pandas as pd

    df = pd.read_excel("studentdata.xlsx")

    student_id = int(input("Enter the student id: "))
    name = input("Enter the name: ")
    score = int(input("Enter the Score: "))
    rank = int(input("Enter the rank: "))

    data = {
        "Student id": student_id,
        "Name": name,
        "Score": score,
        "Rank": rank
    }

    df1 = pd.DataFrame([data])

    df = pd.concat([df, df1], ignore_index=True)

    # 🔴 Save updated dataframe back to Excel
    df.to_excel("studentdata.xlsx", index=False)

    return df

In [37]:
add_student()

   Student id    Name  Score  Rank
0         101   Vinay    540     4
1         102    Anup    560     3
2         103   Abdul    620     1
3         104  Ganesh    600     2
4         117    neha    500     8
5         119   mogya    516     7